name: ssbom
summary: ssbom is a software tool to generate SBOMs for chiselled Ubuntu package slices.
description: |
  ssbom consumes the Chisel JsonWall-formatted manifest and generates a software
  bill of materials (SBOM) in SPDX JSON format.
source-code: https://github.com/canonical/ssbom
version: '0.0.1'
grade: devel
base: core24
confinement: strict

parts:
  ssbom:
    plugin: go
    build-snaps: [go/latest/stable]
    source: .
    stage-packages:
      - git

apps:
  ssbom:
    command: bin/ssbom
    plugs: 
      - home
